name: wellmom_app
description: "WellMom - Maternal Health Monitoring App"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.4.10
  dio: ^5.4.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  intl: ^0.20.2
  url_launcher: ^6.2.6
  shared_preferences: ^2.2.3
  image_picker: ^1.0.7
  share_plus: ^12.0.1
  web_socket_channel: ^3.0.1
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  flutter_local_notifications: ^20.0.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  freezed: ^3.2.5
  json_serializable: ^6.7.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/Logo Wellmom.png
  android: true
  ios: true
  fullscreen: true
  android_12:
    image: assets/images/Logo Wellmom.png
    color: "#FFFFFF"
    fullscreen: true
